### ISSUE TITLE
Restructure the docs and create initial files

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/GeoHosting#265]
Te docs need to be restructured to the following. Initial documents need to be recreated:
```
nav:
  - Introduction: index.md
  - Subscription process: subscription.md
  - Dashboard:
      - Hosted Services: dashboard/hosted_services.md
      - Agreements: dashboard/agreements.md
      - Orders: dashboard/orders.md
      - Supports:
          - List: dashboard/supports/list.md
          - Create: dashboard/supports/create.md
      - Profile:
          - View: dashboard/profile/view.md
          - Edit: dashboard/profile/edit.md
  - Products:
      - GeoNode:
          - Introduction: products/geonode/introduction.md
          - Guide: products/geonode/guide.md
      - G3W:
          - Introduction: products/g3w/introduction.md
          - Guide: products/g3w/guide.md
      - BIMS:
          - Introduction: products/bims/introduction.md
          - Guide: products/bims/guide.md
      - GeoServer:
          - Introduction: products/geoserver/introduction.md
          - Guide: products/geoserver/guide.md
      - GeoSight:
          - Introduction: products/geosight/introduction.md
          - Guide: products/geosight/guide.md
  - Developer Guide:
      - GeoHosting: developer/geo_hosting.md
      - GeoNode: developer/geonode.md
      - G3W: developer/g3w.md
      - BIMS: developer/bims.md
      - GeoServer: developer/geoserver.md
      - GeoSight: developer/geosight.md
```
